# Generated by Django 3.2 on 2021-04-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210419_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_views',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
