# Generated by Django 3.2 on 2021-04-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_post_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
