# Generated by Django 3.2 on 2021-04-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomment',
            name='sub_com_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.profile'),
        ),
    ]
