# Generated by Django 3.2 on 2021-04-21 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0011_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='category',
        ),
        migrations.AlterField(
            model_name='banner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
