# Generated by Django 3.2 on 2021-04-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.TextField(),
        ),
    ]
